on:
  push:
    branches: [main]
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  build:
    name: Fetch data
    runs-on: ubuntu-latest
    env:
      URL2: ${{ secrets.URL2 }}

    steps:
      - name: Checkout repository
        run: git clone https://github.com/${{ github.repository }}.git .

      - name: Install Node.js
        run: |
          curl -sL https://deb.nodesource.com/setup_20.x | sudo -E bash -
          sudo apt-get install -y nodejs

      - name: Install dependencies
        run: npm ci

      - name: Run node file
        run: npm run build --if-present

      - name: Sleep for a few seconds
        run: sleep 10s

      - name: Commit report
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}

          git add -A
          git commit -m "⭐ Автоматическое Обновление 💥" || echo "No changes to commit"
          git push || echo "No changes to push"
