name: Fetch and Process Data

on:
  push:
    branches: [main]  # Триггер при каждом коммите в ветку main
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"  # Триггер по расписанию каждые 5 минут

jobs:
  build:
    name: Fetch data
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        run: git clone https://github.com/${{ github.repository }} repo

      - name: Set up Python
        run: |
          sudo apt-get update
          sudo apt-get install python3 python3-pip -y
          python3 -m pip install --upgrade pip

      - name: Install dependencies
        working-directory: ./repo
        run: pip3 install requests

      - name: Run Python script
        working-directory: ./repo
        run: python3 main.py

      - name: Commit report
        working-directory: ./repo
        run: |
          git config --global user.name 'atageldi194229'
          git config --global user.email 'atageldi194229@gmail.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}

          git add -A
          git commit -m "Automated data update" || echo "No changes to commit"
          git push || echo "No changes to push"
